import Foundation

final class Logger {
    @Dependency(\.printer)
    private var printer: Printer
    @Dependency(\.errorPrinter)
    private var errorPrinter: Printer
    private var numberOfMutationPoints: Int = 0
    private var progressBar: ProgressBar!
    /// How many lines the progress bar takes. Its printer redraws it by moving the cursor up over that many lines.
    private static let progressBarLines = 2

    func launched() {
        print(
            """
            \(muterLogoForTerminal)

            Automated mutation testing for Swift 🕳️

            You are running version \("\(version)".bold)

            Want help? Have suggestions? Want to get involved?
             ↳ https://github.com/muter-mutation-testing/muter/issues
            +--------------------------------------------------------+

            """
        )
    }

    func updateCheckStarted() {
        print("🔎 Checking for new versions...")
    }

    func updateCheckFinished(newVersion: String?) {
        if let newVersion {
            print("🎉 New version \(newVersion) available!")
        } else {
            print("✅ You are already using the latest of SwiftMutator")
        }
    }

    func projectCopyStarted() {
        print("✂️ Copying your project to a temporary directory for testing...")
    }

    func projectCopySkippedVanishedFiles(_ paths: [String]) {
        let shown = paths.prefix(5).map { "  \($0)" }
        let more = paths.count > shown.count ? ["  … and \(paths.count - shown.count) more"] : []
        print(
            (["⚠️ Skipped \(paths.count) file(s) that disappeared while your project was being copied:"] + shown + more)
                .joined(separator: "\n")
        )
    }

    func projectCopyFinished(destinationPath: String) {
        print(
            """
            ✅ Finished copying your project to a temporary directory for mutation testing.
            You can find your copied project here:

            \(destinationPath.bold)

            This directory will also serve as a backup for any XCTest logs that are generated by running your test suite.
            """
        )
    }

    func projectCoverageDiscoveryStarted() {
        print("⚙️ Running tests with coverage enabled to determine which files to mutate")
    }

    func projectCoverageDiscoveryFinished(success: Bool) {
        guard success == false else {
            return
        }

        print(
            """
            ❌ Gathering coverage failed.
            Proceeding with mutation testing anyway.
            Pass \("--skip-coverage argument".bold) to disable this step
            """
        )
    }

    func sourceFileDiscoveryStarted() {
        printMessage("🔎 Discovering Swift files which SwiftMutator will analyze...")
    }

    func sourceFileDiscoveryFinished(sourceFileCandidates: [String]) {
        let fileNames = sourceFileCandidates
            .map(URL.init(fileURLWithPath:))
            .map { $0.lastPathComponent }
            .joined(separator: "\n")
            .bold

        print("✅ In total, SwiftMutator discovered \(sourceFileCandidates.count) Swift files\n\n\(fileNames)")
    }

    func mutationsDiscoveryStarted() {
        printMessage("🔎 Analyzing source files to find mutants which can be inserted into your project...")
    }

    func mutationsDiscoveryFinished(mutations: [SchemataMutationMapping]) {
        let numberOfFiles = mutations.count
        var filesSummary: [String: Int] = [:]

        for mutation in mutations {
            numberOfMutationPoints += mutation.mutationSchemata.count
            filesSummary[mutation.fileName, default: 0] += mutation.mutationSchemata.count
        }

        print("✅ In total, SwiftMutator discovered \(numberOfMutationPoints) mutants in \(numberOfFiles) files\n")
        for (fileName, mutantCount) in filesSummary {
            print("\(fileName) (\(mutantCount) mutants)".bold)
        }
    }

    func mutationTestingStarted() {
        printMessage(
            """
            🚀 Mutation testing will now begin
            ⚙️ Running your test suite to determine a baseline for mutation testing...
            """
        )
    }

    func stopAtFirstFailureTurnedOff(reason: String) {
        print("⚠️ stopAtFirstFailure is off for this run, so every mutant's tests run to the end: \(reason)")
    }

    func resultsFileCreated(atPath path: String) {
        print("💾 SwiftMutator saves each mutant's result as it finishes, in \(path.bold)")
    }

    func resultsFileUnavailable(reason: String) {
        print(
            "⚠️ SwiftMutator can't save each mutant's result as it goes: \(reason). "
                + "The report at the end doesn't depend on it."
        )
        leaveRoomForTheProgressBar()
    }

    func resultsFileKept(atPath path: String) {
        print("💾 Each mutant's result is in \(path.bold)")
    }

    func newMutationTestLogAvailable(mutationTestLog: MutationTestLog) {
        if mutationTestLog.mutationPoint == nil {
            print(
                """
                📊 Determined baseline for mutation testing.
                🧟 SwiftMutator is now going to apply each mutant one at a time and run your test suite for each mutant.
                📃 After this step, SwiftMutator will generate a report detailing the efficacy of your test suite.
                ☕️ This step may take a while.

                """
            )

            progressBar = ProgressBar(
                count: numberOfMutationPoints,
                configuration: [
                    ProgressString(string: "Inserting mutant"),
                    ProgressOneIndexed(),
                    ProgressString(string: "\nPercentage complete: "),
                    ProgressPercent(),
                    ColoredProgressBarLine(barLength: 50),
                    SimpleTimeEstimate(
                        initialEstimate: Double(mutationTestLog.remainingMutationPointsCount!) * mutationTestLog
                            .timePerBuildTestCycle!
                    ),
                ],
                printer: ProgressBarMultilineTerminalPrinter(numberOfLines: Self.progressBarLines)
            )
        }

        progressBar.next()
    }

    func mutationTestingFinished(
        report: String,
        reportPath: String,
        isExportingReport: Bool,
        didSaveReport: Bool
    ) {
        print("🏁 SwiftMutator finished running!")

        guard isExportingReport else {
            return print(
                """
                📝 SwiftMutator's report

                \(report)
                """
            )
        }

        if didSaveReport {
            print("📝 Report generated: \(reportPath.bold)")
        } else {
            print(report)
            print("\n")
            print("Could not save report!")
        }
    }

    /// What mutation testing tested before it stopped early, where its partial report is, if it has one, where each
    /// result is, and the command that makes a report of them all. On standard error: it reaches the terminal even when
    /// a `| tee` that the same Ctrl-C ended has closed standard output. An abort's error follows on standard output.
    func mutationTestingEndedEarly(
        _ earlyEnd: EarlyEnd,
        partialReport: (path: String, saved: Bool)?,
        resultsFile: String?
    ) {
        let tested = earlyEnd.outcome.mutations.count
        let stoppedBy = earlyEnd.reason == .interrupted ? "by \(earlyEnd.detail ?? "a signal")" : "by the error below"
        var lines: [String]
        if tested == 0 {
            lines = ["⏹ Stopped \(stoppedBy) before any of \(earlyEnd.discovered) mutants finished."]
        } else {
            let score = mutationScore(from: earlyEnd.outcome.mutations.map(\.testSuiteOutcome))
            lines = [
                "⏹ Stopped \(stoppedBy) after testing \(tested) of \(earlyEnd.discovered) mutants. "
                    + "Mutation score so far: \(score)%.",
            ]
        }
        if let partialReport {
            lines.append(
                partialReport.saved
                    ? "📝 Partial report: \(partialReport.path.bold)"
                    : "⚠️ Could not save the partial report to \(partialReport.path)"
            )
        }
        if let resultsFile {
            lines.append("💾 Each tested mutant's result is in \(resultsFile.bold)")
            if tested > 0 {
                lines.append("📝 Full report: swift-mutator report \(Self.shellQuoted(resultsFile))")
            }
        }
        lines.forEach(errorPrinter)
    }

    /// `text` as one word for a POSIX shell, so that a printed command pastes whatever the path holds: log folders are
    /// named like `Oct 4, 2026 at 1:16 PM`.
    static func shellQuoted(_ text: String) -> String {
        "'" + text.replacingOccurrences(of: "'", with: #"'\''"#) + "'"
    }

    func testPlanFileCreated(atPath path: String?) {
        if let path {
            print("💾 Mutation test plan created: \(path)")
        } else {
            print("💾 Mutation test plan created")
        }
    }

    func configurationFileCreated(atPath path: String?) {
        if let path {
            print("💾 Configuration file created at: \(path)")
        }
    }

    func muterMutationTestPlanLoaded() {
        print("⬆️ SwiftMutator mutation test plan loaded")
    }

    /// Every line Muter logs goes through here, and so through the injected `printer`.
    ///
    /// The printer used to be a property also named `print`. Calls to `print("…")` inside this
    /// type were then ambiguous between that property and this method, and newer compilers
    /// pick this method, which wrote straight to standard output and bypassed the printer.
    func print(_ message: String) {
        printer(message)
    }

    private func printMessage(_ message: String) {
        print("+-----------------+")
        print(message)
    }

    /// Follows a message printed while the progress bar is still to be redrawn with as many empty lines as the bar
    /// takes. The redraw moves the cursor up over those lines rather than over the end of the message. The bar's
    /// `next()` redraws it only while `element <= count`, so the bar's last redraw needs no room after it.
    private func leaveRoomForTheProgressBar() {
        guard let progressBar, progressBar.element <= progressBar.count else {
            return
        }
        for _ in 0 ..< Self.progressBarLines {
            print("")
        }
    }
}
