import Foundation

final class Logger {
    @Dependency(\.printer)
    private var printer: Printer
    @Dependency(\.errorPrinter)
    private var errorPrinter: Printer
    @Dependency(\.instant)
    private var instant: Instant
    /// When the mutants started, which the progress bar's estimate measures their rate from.
    private var mutantRunsStartedAt: DispatchTime?
    /// How many mutants the progress bar counts: those discovered, or those a resumed run has left to test.
    private(set) var numberOfMutationPoints: Int = 0
    private var progressBar: ProgressBar!
    /// How many lines the progress bar takes. Its printer redraws it by moving the cursor up over that many lines.
    private static let progressBarLines = 2

    func launched() {
        print(
            """
            \(muterLogoForTerminal)

            Automated mutation testing for Swift 🕳️

            You are running version \("\(version)".bold)

            Want help? Have suggestions? Want to get involved?
             ↳ https://github.com/muter-mutation-testing/muter/issues
            +--------------------------------------------------------+

            """
        )
    }

    func updateCheckStarted() {
        print("🔎 Checking for new versions...")
    }

    func updateCheckFinished(newVersion: String?) {
        if let newVersion {
            print("🎉 New version \(newVersion) available!")
        } else {
            print("✅ You are already using the latest of SwiftMutator")
        }
    }

    func projectCopyStarted() {
        print("✂️ Copying your project to a temporary directory for testing...")
    }

    func projectCopySkippedVanishedFiles(_ paths: [String]) {
        let shown = paths.prefix(5).map { "  \($0)" }
        let more = paths.count > shown.count ? ["  … and \(paths.count - shown.count) more"] : []
        print(
            (["⚠️ Skipped \(paths.count) file(s) that disappeared while your project was being copied:"] + shown + more)
                .joined(separator: "\n")
        )
    }

    func projectCopyFinished(destinationPath: String) {
        print(
            """
            ✅ Finished copying your project to a temporary directory for mutation testing.
            You can find your copied project here:

            \(destinationPath.bold)

            This directory will also serve as a backup for any XCTest logs that are generated by running your test suite.
            """
        )
    }

    func projectCoverageDiscoveryStarted() {
        print("⚙️ Running tests with coverage enabled to determine which files to mutate")
    }

    func projectCoverageDiscoveryFinished(success: Bool) {
        guard success == false else {
            return
        }

        print(
            """
            ❌ Gathering coverage failed.
            Proceeding with mutation testing anyway.
            Pass \("--skip-coverage argument".bold) to disable this step
            """
        )
    }

    func sourceFileDiscoveryStarted() {
        printMessage("🔎 Discovering Swift files which SwiftMutator will analyze...")
    }

    func sourceFileDiscoveryFinished(sourceFileCandidates: [String]) {
        let fileNames = sourceFileCandidates
            .map(URL.init(fileURLWithPath:))
            .map { $0.lastPathComponent }
            .joined(separator: "\n")
            .bold

        print("✅ In total, SwiftMutator discovered \(sourceFileCandidates.count) Swift files\n\n\(fileNames)")
    }

    func mutationsDiscoveryStarted() {
        printMessage("🔎 Analyzing source files to find mutants which can be inserted into your project...")
    }

    func mutationsDiscoveryFinished(mutations: [SchemataMutationMapping]) {
        let numberOfFiles = mutations.count
        var filesSummary: [String: Int] = [:]

        for mutation in mutations {
            numberOfMutationPoints += mutation.mutationSchemata.count
            filesSummary[mutation.fileName, default: 0] += mutation.mutationSchemata.count
        }

        print("✅ In total, SwiftMutator discovered \(numberOfMutationPoints) mutants in \(numberOfFiles) files\n")
        for (fileName, mutantCount) in filesSummary {
            print("\(fileName) (\(mutantCount) mutants)".bold)
        }
    }

    /// How many of a resumed run's results still hold, and how many mutants are left to test and why; then each change
    /// no result depends on, and what `--force-resume` and `--resume-ignoring` let through. The progress bar then
    /// counts only the mutants left to test.
    func resumePlanned(_ summary: ResumeSummary) {
        numberOfMutationPoints = summary.toTest
        let resuming = "♻️ Resuming the run in \(summary.path.bold): "
        if summary.toTest == 0 {
            let reused = summary.reused == 1 ? "its only result still holds" : "all \(summary.reused) results still hold"
            print(resuming + "\(reused), so nothing is left to test.")
        } else {
            let reasons = ResumePlan.Reason.allCases.compactMap { reason in
                summary.retestedBecause[reason].flatMap { $0 > 0 ? Self.retested($0, because: reason) : nil }
            }
            let reused = summary.reused == 1 ? "1 result still holds" : "\(summary.reused) results still hold"
            let left = summary.toTest == 1 ? "1 mutant is" : "\(summary.toTest) mutants are"
            let why = reasons.isEmpty ? "" : " (\(reasons.joined(separator: ", ")))"
            print(resuming + "\(reused), so \(left) left to test\(why).")
        }
        for notice in summary.notices {
            print("ℹ️ \(notice)")
        }
        if !summary.forced.isEmpty {
            let subjects = summary.forced.map { name in
                let subject = ResumeCheck.subject(of: name)
                return subject.hasPrefix("The ") ? "the " + subject.dropFirst(4) : subject
            }
            print("⚠️ Results are reused although \(Self.listed(subjects)) changed (--force-resume).")
        }
        if !summary.waived.isEmpty {
            let named = summary.waived.prefix(ResumeRefusal.changedFilesNamed)
            let others = summary.waived.count - named.count
            let files = summary.waived.count == 1 ? "1 project file" : "\(summary.waived.count) project files"
            print(
                "⚠️ Results are reused although \(files) changed (--resume-ignoring): "
                    + named.joined(separator: ", ") + (others > 0 ? ", and \(others) more" : "")
            )
        }
    }

    /// "5 build errors": how many mutants are tested again for `reason`.
    private static func retested(_ count: Int, because reason: ResumePlan.Reason) -> String {
        let one = count == 1
        switch reason {
        case .notRecorded:
            return "\(count) never tested"
        case .buildError:
            return "\(count) build error\(one ? "" : "s")"
        case .fileChanged:
            return "\(count) in \(one ? "a changed file" : "changed files")"
        case .mutationChanged:
            return "\(count) changed mutation\(one ? "" : "s")"
        case .repeated:
            return "\(count) repeated in \(one ? "its" : "their") file"
        }
    }

    /// "a, b and c".
    private static func listed(_ items: [String]) -> String {
        guard let last = items.last, items.count > 1 else { return items.first ?? "" }
        return items.dropLast().joined(separator: ", ") + " and " + last
    }

    func mutantRunsStarted() {
        mutantRunsStartedAt = instant()
    }

    func mutationTestingStarted() {
        printMessage(
            """
            🚀 Mutation testing will now begin
            ⚙️ Running your test suite to determine a baseline for mutation testing...
            """
        )
    }

    func stopAtFirstFailureTurnedOff(reason: String) {
        print("⚠️ stopAtFirstFailure is off for this run, so every mutant's tests run to the end: \(reason)")
    }

    func resultsFileCreated(atPath path: String) {
        print("💾 SwiftMutator saves each mutant's result as it finishes, in \(path.bold)")
    }

    func resultsFileUnavailable(reason: String) {
        print(
            "⚠️ SwiftMutator can't save each mutant's result as it goes: \(reason). "
                + "The report at the end doesn't depend on it."
        )
        leaveRoomForTheProgressBar()
    }

    func resultsFileKept(atPath path: String) {
        print("💾 Each mutant's result is in \(path.bold)")
    }

    func newMutationTestLogAvailable(mutationTestLog: MutationTestLog) {
        if mutationTestLog.mutationPoint == nil {
            print(
                """
                📊 Determined baseline for mutation testing.
                🧟 SwiftMutator is now going to apply each mutant one at a time and run your test suite for each mutant.
                📃 After this step, SwiftMutator will generate a report detailing the efficacy of your test suite.
                ☕️ This step may take a while.

                """
            )

            progressBar = ProgressBar(
                count: numberOfMutationPoints,
                configuration: [
                    ProgressString(string: "Inserting mutant"),
                    ProgressOneIndexed(),
                    ProgressString(string: "\nPercentage complete: "),
                    ProgressPercent(),
                    ColoredProgressBarLine(barLength: 50),
                    SimpleTimeEstimate(
                        firstEstimate: Self.initialEstimate(
                            remaining: mutationTestLog.remainingMutationPointsCount!,
                            cycle: mutationTestLog.testRunSeconds ?? mutationTestLog.timePerBuildTestCycle!,
                            workers: mutationTestLog.workers
                        ),
                        workers: mutationTestLog.workers,
                        elapsed: { [weak self] in self?.secondsSinceMutantRunsStarted() }
                    ),
                ],
                printer: ProgressBarMultilineTerminalPrinter(numberOfLines: Self.progressBarLines)
            )
        }

        progressBar.next()
    }

    /// The seconds since the mutants started, or nil before they have.
    private func secondsSinceMutantRunsStarted() -> TimeInterval? {
        guard let start = mutantRunsStartedAt else { return nil }
        let now = instant()
        guard now >= start else { return 0 }
        return Double(now.uptimeNanoseconds - start.uptimeNanoseconds) / 1_000_000_000
    }

    /// The time left with `tested` of `total` mutants tested on `workers` workers, `elapsed` seconds after they started.
    /// Until as many mutants have finished as there are workers, about one each, a rate would count the mutants still
    /// running as if none had started, so the `firstEstimate` counts down. After that, it is the time per mutant so far
    /// times the mutants left.
    static func secondsLeft(
        tested: Int,
        of total: Int,
        workers: Int,
        elapsed: TimeInterval?,
        firstEstimate: TimeInterval
    ) -> TimeInterval {
        let left = total - tested
        guard left > 0 else { return 0 }
        guard let elapsed, tested > 0, tested >= min(max(workers, 1), total) else {
            return max(firstEstimate - (elapsed ?? 0), 0)
        }
        return elapsed / Double(tested) * Double(left)
    }

    /// The time left before any mutant has finished. Each worker tests its share of the `remaining` mutants, a `cycle`
    /// for each, while the others test theirs, so the largest share sets it. The cycle is the timed test run, which skips
    /// the build as a mutant's run does, or else the baseline, build included.
    static func initialEstimate(remaining: Int, cycle: TimeInterval, workers: Int) -> TimeInterval {
        let largestShare = ceil(Double(remaining) / Double(max(workers, 1)))
        return largestShare * cycle
    }

    /// Where the report went, or the report itself, then the report's `suspectWarning`
    /// (`KillingTestSummary.warning(for:)`), if it has one: the run's last word on its score.
    func mutationTestingFinished(
        report: String,
        reportPath: String,
        isExportingReport: Bool,
        didSaveReport: Bool,
        suspectWarning: String?
    ) {
        print("🏁 SwiftMutator finished running!")

        if !isExportingReport {
            print(
                """
                📝 SwiftMutator's report

                \(report)
                """
            )
        } else if didSaveReport {
            print("📝 Report generated: \(reportPath.bold)")
        } else {
            print(report)
            print("\n")
            print("Could not save report!")
        }

        if let suspectWarning {
            print("⚠️ \(suspectWarning)")
        }
    }

    /// What mutation testing tested before it stopped early, and the warning of suspect tests its report gives, if it
    /// gives one, then where its partial report is, if it has one, where each result is, the command that makes a
    /// report of them all, and the command that continues the run. A resumed session counts the mutants it tested apart
    /// from the results it kept. On standard error: it reaches the terminal even when a `| tee` that the same Ctrl-C
    /// ended has closed standard output. An abort's error follows on standard output.
    func mutationTestingEndedEarly(
        _ earlyEnd: EarlyEnd,
        partialReport: (path: String, saved: Bool)?,
        resultsFile: String?,
        continueCommand: String?
    ) {
        let results = earlyEnd.outcome.mutations.count
        var lines = [Self.stopped(earlyEnd)]
        if let suspectWarning = KillingTestSummary.warning(for: earlyEnd.outcome) {
            lines.append("⚠️ \(suspectWarning)")
        }
        if let partialReport {
            lines.append(
                partialReport.saved
                    ? "📝 Partial report: \(partialReport.path.bold)"
                    : "⚠️ Could not save the partial report to \(partialReport.path)"
            )
        }
        if let resultsFile {
            lines.append("💾 Each tested mutant's result is in \(resultsFile.bold)")
            // Without a result, the report would be empty, and a resume would keep nothing a new run doesn't.
            if results > 0 {
                lines.append("📝 Full report: swift-mutator report \(Self.shellQuoted(resultsFile))")
                if let continueCommand {
                    lines.append("▶️ Continue: \(continueCommand)")
                }
            }
        }
        lines.forEach(errorPrinter)
    }

    /// "⏹ Stopped by SIGINT after testing 3 of 9 mutants. Mutation score so far: 50%." A resumed session says how many
    /// of the mutants left it tested, and how many of every mutant have a result, kept or tested; the score is theirs.
    private static func stopped(_ earlyEnd: EarlyEnd) -> String {
        let stoppedBy = earlyEnd.reason == .interrupted ? "by \(earlyEnd.detail ?? "a signal")" : "by the error below"
        let results = earlyEnd.outcome.mutations.count
        guard results > 0 else {
            return "⏹ Stopped \(stoppedBy) before any of \(earlyEnd.discovered) mutants finished."
        }
        let score = "Mutation score so far: \(mutationScore(from: earlyEnd.outcome.mutations.map(\.testSuiteOutcome)))%."
        let tested = results - earlyEnd.reused
        guard earlyEnd.reused > 0 else {
            return "⏹ Stopped \(stoppedBy) after testing \(tested) of \(earlyEnd.discovered) mutants. " + score
        }
        let left = earlyEnd.discovered - earlyEnd.reused
        let progress = tested == 0
            ? "before any of the \(left) mutants left finished"
            : "after testing \(tested) of the \(left) mutants left"
        return "⏹ Stopped \(stoppedBy) \(progress): \(results) of \(earlyEnd.discovered) have results. " + score
    }

    /// `text` as one word for a POSIX shell, so that a printed command pastes whatever the path holds: log folders are
    /// named like `Oct 4, 2026 at 1:16 PM`.
    static func shellQuoted(_ text: String) -> String {
        "'" + text.replacingOccurrences(of: "'", with: #"'\''"#) + "'"
    }

    /// The characters a POSIX shell gives no meaning to, in any place in a word that isn't a command's name.
    private static let plainWordCharacters = Set(
        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_@%+=:,./-".unicodeScalars
    )

    /// `text` as it is if a POSIX shell reads it as that one word, and quoted as `shellQuoted` quotes it otherwise:
    /// a printed command keeps the arguments it repeats as readable as they were typed.
    static func shellWord(_ text: String) -> String {
        guard !text.isEmpty, text.unicodeScalars.allSatisfy(plainWordCharacters.contains) else {
            return shellQuoted(text)
        }
        return text
    }

    func testPlanFileCreated(atPath path: String?) {
        if let path {
            print("💾 Mutation test plan created: \(path)")
        } else {
            print("💾 Mutation test plan created")
        }
    }

    func configurationFileCreated(atPath path: String?) {
        if let path {
            print("💾 Configuration file created at: \(path)")
        }
    }

    func muterMutationTestPlanLoaded() {
        print("⬆️ SwiftMutator mutation test plan loaded")
    }

    /// Every line Muter logs goes through here, and so through the injected `printer`.
    ///
    /// The printer used to be a property also named `print`. Calls to `print("…")` inside this
    /// type were then ambiguous between that property and this method, and newer compilers
    /// pick this method, which wrote straight to standard output and bypassed the printer.
    func print(_ message: String) {
        printer(message)
    }

    private func printMessage(_ message: String) {
        print("+-----------------+")
        print(message)
    }

    /// Follows a message printed while the progress bar is still to be redrawn with as many empty lines as the bar
    /// takes. The redraw moves the cursor up over those lines rather than over the end of the message. The bar's
    /// `next()` redraws it only while `element <= count`, so the bar's last redraw needs no room after it.
    private func leaveRoomForTheProgressBar() {
        guard let progressBar, progressBar.element <= progressBar.count else {
            return
        }
        for _ in 0 ..< Self.progressBarLines {
            print("")
        }
    }
}
